import { ipcRenderer } from 'electron';

import type { QdbDesktopApi } from '../../shared/downloader/contracts.js';

const channels = {
  getSourcePriority: 'qdb:preferences:source-priority:get',
  updateSourcePriority: 'qdb:preferences:source-priority:update',
  getExportVisibilityPresets: 'qdb:preferences:export-visibility-presets:get',
  updateExportVisibilityPresets: 'qdb:preferences:export-visibility-presets:update',
  getExportFieldNamePresets: 'qdb:preferences:export-field-name-presets:get',
  updateExportFieldNamePresets: 'qdb:preferences:export-field-name-presets:update',
  getExportConfiguration: 'qdb:preferences:export-configuration:get',
  updateExportConfiguration: 'qdb:preferences:export-configuration:update',
  listCustomBadges: 'qdb:custom-badges:list',
  createCustomBadge: 'qdb:custom-badges:create',
  updateCustomBadge: 'qdb:custom-badges:update',
  deleteCustomBadge: 'qdb:custom-badges:delete',
  updateEntityCustomBadges: 'qdb:custom-badges:update-entities',
  listCombinedCustomBadges: 'qdb:combined-custom-badges:list',
  createCombinedCustomBadge: 'qdb:combined-custom-badges:create',
  updateCombinedCustomBadge: 'qdb:combined-custom-badges:update',
  deleteCombinedCustomBadge: 'qdb:combined-custom-badges:delete',
  updateCombinedEntityCustomBadges: 'qdb:combined-custom-badges:update-entities',
  listProjects: 'qdb:projects:list',
  createProject: 'qdb:projects:create',
  renameProject: 'qdb:projects:rename',
  deleteProject: 'qdb:projects:delete',
  deleteAllProjects: 'qdb:projects:delete-all',
  deleteLeague: 'qdb:leagues:delete',
  deleteLeagues: 'qdb:leagues:delete-many',
  updateLeagueCountries: 'qdb:leagues:update-country-many',
  updateLeagueTiers: 'qdb:leagues:update-tier-many',
  deleteTeam: 'qdb:teams:delete',
  deleteTeams: 'qdb:teams:delete-many',
  updateTeamCountries: 'qdb:teams:update-country-many',
  deletePlayer: 'qdb:players:delete',
  deletePlayers: 'qdb:players:delete-many',
  previewSourceDataDeletion: 'qdb:data:preview-delete-sources',
  deleteSourceData: 'qdb:data:delete-sources',
  getProjectSummary: 'qdb:projects:summary',
  getEntity: 'qdb:entities:get',
  updateEntityMetadata: 'qdb:entities:update-metadata',
  listEntities: 'qdb:entities:list',
  listEntityFilterOptions: 'qdb:entities:filter-options',
  listCombinedEntityFilterOptions: 'qdb:combined:filter-options',
  listCombinedEntities: 'qdb:combined:list',
  listCombineTeamCandidates: 'qdb:combined:team-candidates',
  previewTeamCombination: 'qdb:combined:preview-team',
  commitTeamCombination: 'qdb:combined:commit-team',
  deleteCombinedEntity: 'qdb:combined:delete',
  deleteCombinedLeagues: 'qdb:combined:leagues:delete-many',
  deleteCombinedTeams: 'qdb:combined:teams:delete-many',
  deleteCombinedPlayers: 'qdb:combined:players:delete-many',
  previewLeague: 'qdb:scrape:league',
  previewTeam: 'qdb:scrape:team',
  previewTeams: 'qdb:scrape:teams',
  cancelScrape: 'qdb:scrape:cancel',
  previewImportChanges: 'qdb:import:preview-changes',
  commitImport: 'qdb:import:commit',
  getExportDestination: 'qdb:export:get-destination',
  chooseExportDirectory: 'qdb:export:choose-directory',
  exportProject: 'qdb:export:project',
  openExportDirectory: 'qdb:export:open-directory',
  scrapeProgress: 'qdb:scrape:progress',
} as const;

export const downloaderApi: QdbDesktopApi = {
  getSourcePriority: () => ipcRenderer.invoke(channels.getSourcePriority),
  updateSourcePriority: (request) => ipcRenderer.invoke(channels.updateSourcePriority, request),
  getExportVisibilityPresets: () => ipcRenderer.invoke(channels.getExportVisibilityPresets),
  updateExportVisibilityPresets: (request) =>
    ipcRenderer.invoke(channels.updateExportVisibilityPresets, request),
  getExportFieldNamePresets: () => ipcRenderer.invoke(channels.getExportFieldNamePresets),
  updateExportFieldNamePresets: (request) =>
    ipcRenderer.invoke(channels.updateExportFieldNamePresets, request),
  getExportConfiguration: () => ipcRenderer.invoke(channels.getExportConfiguration),
  updateExportConfiguration: (request) =>
    ipcRenderer.invoke(channels.updateExportConfiguration, request),
  listCustomBadges: () => ipcRenderer.invoke(channels.listCustomBadges),
  createCustomBadge: (request) => ipcRenderer.invoke(channels.createCustomBadge, request),
  updateCustomBadge: (request) => ipcRenderer.invoke(channels.updateCustomBadge, request),
  deleteCustomBadge: (request) => ipcRenderer.invoke(channels.deleteCustomBadge, request),
  updateEntityCustomBadges: (request) =>
    ipcRenderer.invoke(channels.updateEntityCustomBadges, request),
  listCombinedCustomBadges: () => ipcRenderer.invoke(channels.listCombinedCustomBadges),
  createCombinedCustomBadge: (request) =>
    ipcRenderer.invoke(channels.createCombinedCustomBadge, request),
  updateCombinedCustomBadge: (request) =>
    ipcRenderer.invoke(channels.updateCombinedCustomBadge, request),
  deleteCombinedCustomBadge: (request) =>
    ipcRenderer.invoke(channels.deleteCombinedCustomBadge, request),
  updateCombinedEntityCustomBadges: (request) =>
    ipcRenderer.invoke(channels.updateCombinedEntityCustomBadges, request),
  listProjects: () => ipcRenderer.invoke(channels.listProjects),
  createProject: (input) => ipcRenderer.invoke(channels.createProject, input),
  renameProject: (request) => ipcRenderer.invoke(channels.renameProject, request),
  deleteProject: (request) => ipcRenderer.invoke(channels.deleteProject, request),
  deleteAllProjects: () => ipcRenderer.invoke(channels.deleteAllProjects),
  deleteLeague: (request) => ipcRenderer.invoke(channels.deleteLeague, request),
  deleteLeagues: (request) => ipcRenderer.invoke(channels.deleteLeagues, request),
  updateLeagueCountries: (request) => ipcRenderer.invoke(channels.updateLeagueCountries, request),
  updateLeagueTiers: (request) => ipcRenderer.invoke(channels.updateLeagueTiers, request),
  deleteTeam: (request) => ipcRenderer.invoke(channels.deleteTeam, request),
  deleteTeams: (request) => ipcRenderer.invoke(channels.deleteTeams, request),
  updateTeamCountries: (request) => ipcRenderer.invoke(channels.updateTeamCountries, request),
  deletePlayer: (request) => ipcRenderer.invoke(channels.deletePlayer, request),
  deletePlayers: (request) => ipcRenderer.invoke(channels.deletePlayers, request),
  previewSourceDataDeletion: (request) =>
    ipcRenderer.invoke(channels.previewSourceDataDeletion, request),
  deleteSourceData: (request) => ipcRenderer.invoke(channels.deleteSourceData, request),
  getProjectSummary: (request) => ipcRenderer.invoke(channels.getProjectSummary, request),
  getEntity: (request) => ipcRenderer.invoke(channels.getEntity, request),
  updateEntityMetadata: (request) => ipcRenderer.invoke(channels.updateEntityMetadata, request),
  listEntities: (request) => ipcRenderer.invoke(channels.listEntities, request),
  listEntityFilterOptions: (request) =>
    ipcRenderer.invoke(channels.listEntityFilterOptions, request),
  listCombinedEntityFilterOptions: (request) =>
    ipcRenderer.invoke(channels.listCombinedEntityFilterOptions, request),
  listCombinedEntities: (request) => ipcRenderer.invoke(channels.listCombinedEntities, request),
  listCombineTeamCandidates: (request) =>
    ipcRenderer.invoke(channels.listCombineTeamCandidates, request),
  previewTeamCombination: (request) => ipcRenderer.invoke(channels.previewTeamCombination, request),
  commitTeamCombination: (request) => ipcRenderer.invoke(channels.commitTeamCombination, request),
  deleteCombinedEntity: (request) => ipcRenderer.invoke(channels.deleteCombinedEntity, request),
  deleteCombinedLeagues: (request) => ipcRenderer.invoke(channels.deleteCombinedLeagues, request),
  deleteCombinedTeams: (request) => ipcRenderer.invoke(channels.deleteCombinedTeams, request),
  deleteCombinedPlayers: (request) => ipcRenderer.invoke(channels.deleteCombinedPlayers, request),
  previewLeague: (request) => ipcRenderer.invoke(channels.previewLeague, request),
  previewTeam: (request) => ipcRenderer.invoke(channels.previewTeam, request),
  previewTeams: (request) => ipcRenderer.invoke(channels.previewTeams, request),
  cancelScrape: (request) => ipcRenderer.invoke(channels.cancelScrape, request),
  previewImportChanges: (request) => ipcRenderer.invoke(channels.previewImportChanges, request),
  commitImport: (request) => ipcRenderer.invoke(channels.commitImport, request),
  getExportDestination: () => ipcRenderer.invoke(channels.getExportDestination),
  chooseExportDirectory: () => ipcRenderer.invoke(channels.chooseExportDirectory),
  exportProject: (request) => ipcRenderer.invoke(channels.exportProject, request),
  openExportDirectory: (request) => ipcRenderer.invoke(channels.openExportDirectory, request),
  onScrapeProgress: (listener) => {
    const handler = (
      _event: Electron.IpcRendererEvent,
      progress: Parameters<typeof listener>[0],
    ): void => listener(progress);
    ipcRenderer.on(channels.scrapeProgress, handler);
    return () => ipcRenderer.removeListener(channels.scrapeProgress, handler);
  },
};
