name: 💾 Restore ESLint Cache
description: Restore the Angular ESLint cache
runs:
  using: composite
  steps:
    - name: 💾 Restore ESLint cache
      uses: actions/cache@v6
      with:
        path: .angular/cache/eslint
        key: eslint-${{ runner.os }}-${{ hashFiles('bun.lock', 'eslint.config.js', 'projects/electron/eslint.config.js', 'projects/docs/eslint.config.js') }}-${{ github.sha }}
        restore-keys: |
          eslint-${{ runner.os }}-${{ hashFiles('bun.lock', 'eslint.config.js', 'projects/electron/eslint.config.js', 'projects/docs/eslint.config.js') }}-
