export interface CityPreset {
  name: string;
  latitude: number;
  longitude: number;
  utcoffset: number;
  isocountrycode: string;
}

export const CITY_PRESETS: CityPreset[] = [
  { name: 'Abidjan', latitude: 5, longitude: -4, utcoffset: 0, isocountrycode: 'CI' },
  { name: 'Abuja', latitude: 9, longitude: 7, utcoffset: 1, isocountrycode: 'NG' },
  { name: 'Accra', latitude: 5, longitude: 0, utcoffset: 0, isocountrycode: 'GH' },
  { name: 'Aden', latitude: 12, longitude: 45, utcoffset: 3, isocountrycode: 'YE' },
  { name: 'Addis Ababa', latitude: 9, longitude: 38, utcoffset: 3, isocountrycode: 'ET' },
  { name: 'Aktobe', latitude: 50, longitude: 57, utcoffset: 5, isocountrycode: 'KZ' },
  { name: 'Almaty', latitude: 43, longitude: 77, utcoffset: 6, isocountrycode: 'KZ' },
  { name: 'Aleppo', latitude: 36, longitude: 37, utcoffset: 2, isocountrycode: 'SY' },
  { name: 'Algiers', latitude: 37, longitude: 3, utcoffset: 1, isocountrycode: 'DZ' },
  { name: 'Amman', latitude: 32, longitude: 36, utcoffset: 2, isocountrycode: 'JO' },
  { name: 'Amsterdam', latitude: 52, longitude: 5, utcoffset: 1, isocountrycode: 'NL' },
  { name: 'Andorra la Vella', latitude: 42, longitude: 1, utcoffset: 1, isocountrycode: 'AD' },
  { name: 'Ankara', latitude: 40, longitude: 33, utcoffset: 3, isocountrycode: 'TR' },
  { name: 'Antananarivo', latitude: -18, longitude: 47, utcoffset: 3, isocountrycode: 'MG' },
  { name: 'Aarhus', latitude: 56, longitude: 10, utcoffset: 1, isocountrycode: 'DK' },
  { name: 'Akureyri', latitude: 66, longitude: -18, utcoffset: 0, isocountrycode: 'IS' },
  { name: 'Asmara', latitude: 15, longitude: 39, utcoffset: 3, isocountrycode: 'ER' },
  { name: 'Asgabad', latitude: 38, longitude: 58, utcoffset: 5, isocountrycode: 'TM' },
  { name: 'Asmara', latitude: 15, longitude: 39, utcoffset: 3, isocountrycode: 'ER' },
  { name: 'Aswan', latitude: 24, longitude: 32, utcoffset: 2, isocountrycode: 'EG' },
  { name: 'Astana', latitude: 51, longitude: 71, utcoffset: 6, isocountrycode: 'KZ' },
  { name: 'Astrakhan', latitude: 46, longitude: 48, utcoffset: 4, isocountrycode: 'RU' },
  { name: 'Asuncion', latitude: -25, longitude: -57, utcoffset: -4, isocountrycode: 'PY' },
  { name: 'Athens', latitude: 38, longitude: 23, utcoffset: 2, isocountrycode: 'GR' },
  { name: 'Auckland', latitude: -37, longitude: 175, utcoffset: 12, isocountrycode: 'NZ' },
  { name: 'Baghdad', latitude: 33, longitude: 44, utcoffset: 3, isocountrycode: 'IQ' },
  { name: 'Baku', latitude: 40, longitude: 49, utcoffset: 4, isocountrycode: 'AZ' },
  { name: 'Bamako', latitude: 12, longitude: -8, utcoffset: 0, isocountrycode: 'ML' },
  { name: 'Bangkok', latitude: 14, longitude: 100, utcoffset: 7, isocountrycode: 'TH' },
  { name: 'Bangui', latitude: 4, longitude: 18, utcoffset: 1, isocountrycode: 'CF' },
  { name: 'Bari', latitude: 41, longitude: 16, utcoffset: 1, isocountrycode: 'IT' },
  { name: 'Barcelona', latitude: 41, longitude: 2, utcoffset: 1, isocountrycode: 'ES' },
  { name: 'Basra', latitude: 30, longitude: 47, utcoffset: 3, isocountrycode: 'IQ' },
  { name: 'Belfast', latitude: 54, longitude: -6, utcoffset: 0, isocountrycode: 'GB' },
  { name: 'Belize City', latitude: 17, longitude: -88, utcoffset: -6, isocountrycode: 'BZ' },
  { name: 'Beijing', latitude: 40, longitude: 116, utcoffset: 8, isocountrycode: 'CN' },
  { name: 'Beirut', latitude: 34, longitude: 36, utcoffset: 2, isocountrycode: 'LB' },
  { name: 'Belgrade', latitude: 44, longitude: 20, utcoffset: 1, isocountrycode: 'RS' },
  { name: 'Bern', latitude: 46, longitude: 7, utcoffset: 1, isocountrycode: 'CH' },
  { name: 'Bengaluru', latitude: 13, longitude: 77, utcoffset: 6, isocountrycode: 'IN' },
  { name: 'Benghazi', latitude: 32, longitude: 20, utcoffset: 2, isocountrycode: 'LY' },
  { name: 'Berlin', latitude: 52, longitude: 13, utcoffset: 1, isocountrycode: 'DE' },
  { name: 'Bergen', latitude: 60, longitude: 5, utcoffset: 2, isocountrycode: 'NO' },
  { name: 'Bremen', latitude: 53, longitude: 8, utcoffset: 1, isocountrycode: 'DE' },
  { name: 'Bishkek', latitude: 43, longitude: 75, utcoffset: 6, isocountrycode: 'KG' },
  { name: 'Brest', latitude: 52, longitude: 23, utcoffset: 3, isocountrycode: 'BY' },
  { name: 'Bratislava', latitude: 48, longitude: 17, utcoffset: 1, isocountrycode: 'SK' },
  { name: 'Brno', latitude: 49, longitude: 16, utcoffset: 1, isocountrycode: 'CZ' },
  { name: 'Brazzaville', latitude: -4, longitude: 15, utcoffset: 1, isocountrycode: 'CG' },
  { name: 'Brussels', latitude: 51, longitude: 4, utcoffset: 1, isocountrycode: 'BE' },
  { name: 'Bucharest', latitude: 44, longitude: 26, utcoffset: 2, isocountrycode: 'RO' },
  { name: 'Budapest', latitude: 47, longitude: 19, utcoffset: 1, isocountrycode: 'HU' },
  { name: 'Buenos Aires', latitude: -34, longitude: -58, utcoffset: -3, isocountrycode: 'AR' },
  { name: 'Burgas', latitude: 42, longitude: 27, utcoffset: 2, isocountrycode: 'BG' },
  { name: 'Cairo', latitude: 30, longitude: 31, utcoffset: 2, isocountrycode: 'EG' },
  { name: 'Calgary', latitude: 51, longitude: -114, utcoffset: -7, isocountrycode: 'CA' },
  { name: 'Cape Town', latitude: -34, longitude: 18, utcoffset: 2, isocountrycode: 'ZA' },
  { name: 'Caracas', latitude: 11, longitude: -67, utcoffset: -4, isocountrycode: 'VE' },
  { name: 'Cardiff', latitude: 51, longitude: -3, utcoffset: 0, isocountrycode: 'GB' },
  { name: 'Chernivtsy', latitude: 48, longitude: 25, utcoffset: 2, isocountrycode: 'UA' },
  { name: 'Chelyabinsk', latitude: 55, longitude: 61, utcoffset: 5, isocountrycode: 'RU' },
  { name: 'Cherkasy', latitude: 49, longitude: 32, utcoffset: 2, isocountrycode: 'UA' },
  { name: 'Chicago', latitude: 41, longitude: -87, utcoffset: -6, isocountrycode: 'US' },
  { name: 'Chisinau', latitude: 47, longitude: 29, utcoffset: 2, isocountrycode: 'MD' },
  {
    name: 'Ciudad de Guatemala',
    latitude: 15,
    longitude: -90,
    utcoffset: -6,
    isocountrycode: 'GT',
  },
  { name: 'Cluj', latitude: 46, longitude: 23, utcoffset: 2, isocountrycode: 'RO' },
  { name: 'Colombo', latitude: 6, longitude: 79, utcoffset: 6, isocountrycode: 'LK' },
  { name: 'Conakry', latitude: 9, longitude: -13, utcoffset: 0, isocountrycode: 'GN' },
  { name: 'Copenhagen', latitude: 55, longitude: 12, utcoffset: 1, isocountrycode: 'DK' },
  { name: 'Cork', latitude: 51, longitude: -8, utcoffset: 0, isocountrycode: 'IE' },
  { name: 'Dallas', latitude: 32, longitude: -96, utcoffset: -6, isocountrycode: 'US' },
  { name: 'Damascus', latitude: 33, longitude: 36, utcoffset: 2, isocountrycode: 'SY' },
  { name: 'Dakar', latitude: 14, longitude: -17, utcoffset: 0, isocountrycode: 'SN' },
  { name: 'Davao City', latitude: 7, longitude: 125, utcoffset: 8, isocountrycode: 'PH' },
  { name: 'Debrecen', latitude: 47, longitude: 21, utcoffset: 1, isocountrycode: 'HU' },
  { name: 'Dnipro', latitude: 48, longitude: 35, utcoffset: 2, isocountrycode: 'UA' },
  { name: 'Djibouti', latitude: 11, longitude: 43, utcoffset: 3, isocountrycode: 'DJ' },
  { name: 'Daugavpils', latitude: 55, longitude: 26, utcoffset: 3, isocountrycode: 'LV' },
  { name: 'Dhaka', latitude: 24, longitude: 90, utcoffset: 6, isocountrycode: 'BD' },
  { name: 'Donetsk', latitude: 48, longitude: 38, utcoffset: 3, isocountrycode: 'UA' },
  { name: 'Dodoma', latitude: -6, longitude: 36, utcoffset: 3, isocountrycode: 'TZ' },
  { name: 'Doha', latitude: 25, longitude: 51, utcoffset: 3, isocountrycode: 'QA' },
  { name: 'Dubai', latitude: 25, longitude: 55, utcoffset: 4, isocountrycode: 'AE' },
  { name: 'Dublin', latitude: 53, longitude: -6, utcoffset: 0, isocountrycode: 'IE' },
  { name: 'Dushanbe', latitude: 39, longitude: 69, utcoffset: 5, isocountrycode: 'TJ' },
  { name: 'Freetown', latitude: 8, longitude: -13, utcoffset: 0, isocountrycode: 'SL' },
  { name: 'Frankfurt am Main', latitude: 50, longitude: 9, utcoffset: 1, isocountrycode: 'DE' },
  { name: 'Gaborone', latitude: -24, longitude: 26, utcoffset: 2, isocountrycode: 'BW' },
  { name: 'Gdansk', latitude: 54, longitude: 18, utcoffset: 1, isocountrycode: 'PL' },
  { name: 'Georgetown', latitude: 6, longitude: -58, utcoffset: -4, isocountrycode: 'GY' },
  { name: 'Genova', latitude: 44, longitude: 8, utcoffset: 1, isocountrycode: 'IT' },
  { name: 'Glasgow', latitude: 56, longitude: -4, utcoffset: 0, isocountrycode: 'GB' },
  { name: 'Gitega', latitude: -3, longitude: 29, utcoffset: 2, isocountrycode: 'BI' },
  { name: 'Grodno', latitude: 53, longitude: 24, utcoffset: 3, isocountrycode: 'BY' },
  { name: 'Groningen', latitude: 53, longitude: 6, utcoffset: 1, isocountrycode: 'NL' },
  { name: 'Gothenburg', latitude: 58, longitude: 12, utcoffset: 1, isocountrycode: 'SE' },
  { name: 'Graz', latitude: 47, longitude: 15, utcoffset: 1, isocountrycode: 'AT' },
  { name: 'Hamburg', latitude: 54, longitude: 10, utcoffset: 1, isocountrycode: 'DE' },
  { name: 'Hanoi', latitude: 21, longitude: 106, utcoffset: 7, isocountrycode: 'VN' },
  { name: 'Harare', latitude: -17, longitude: 31, utcoffset: 2, isocountrycode: 'ZW' },
  { name: 'Harbin', latitude: 45, longitude: 126, utcoffset: 8, isocountrycode: 'CN' },
  { name: 'Helsinki', latitude: 60, longitude: 25, utcoffset: 2, isocountrycode: 'FI' },
  { name: 'Heraklion', latitude: 35, longitude: 25, utcoffset: 2, isocountrycode: 'GR' },
  { name: 'Hradec Králové', latitude: 50, longitude: 15, utcoffset: 1, isocountrycode: 'CZ' },
  { name: 'Ho Chi Minh', latitude: 11, longitude: 107, utcoffset: 7, isocountrycode: 'VN' },
  { name: 'Hong Kong', latitude: 22, longitude: 114, utcoffset: 8, isocountrycode: 'HK' },
  { name: 'Homel', latitude: 52, longitude: 31, utcoffset: 3, isocountrycode: 'BY' },
  { name: 'Innsbruck', latitude: 47, longitude: 11, utcoffset: 1, isocountrycode: 'AT' },
  { name: 'Irkutsk', latitude: 52, longitude: 104, utcoffset: 8, isocountrycode: 'RU' },
  { name: 'Isfahan', latitude: 32, longitude: 51, utcoffset: 3, isocountrycode: 'IR' },
  { name: 'Islamabad', latitude: 33, longitude: 73, utcoffset: 5, isocountrycode: 'PK' },
  { name: 'Istanbul', latitude: 41, longitude: 29, utcoffset: 3, isocountrycode: 'TR' },
  { name: 'Izmir', latitude: 38, longitude: 27, utcoffset: 3, isocountrycode: 'TR' },
  { name: 'Jakarta', latitude: -6, longitude: 106, utcoffset: 7, isocountrycode: 'ID' },
  { name: 'Jeddah', latitude: 21, longitude: 39, utcoffset: 3, isocountrycode: 'SA' },
  { name: 'Jerusalem', latitude: 31, longitude: 35, utcoffset: 2, isocountrycode: 'IL' },
  { name: 'Juba', latitude: 4, longitude: 31, utcoffset: 3, isocountrycode: 'SS' },
  { name: 'Kabul', latitude: 34, longitude: 69, utcoffset: 4, isocountrycode: 'AF' },
  { name: 'Kampala', latitude: 0, longitude: 32, utcoffset: 3, isocountrycode: 'UG' },
  { name: 'Kalmar', latitude: 56, longitude: 16, utcoffset: 2, isocountrycode: 'SE' },
  { name: 'Kaliningrad', latitude: 54, longitude: 20, utcoffset: 2, isocountrycode: 'RU' },
  { name: 'Karachi', latitude: 25, longitude: 67, utcoffset: 5, isocountrycode: 'PK' },
  { name: 'Kathmandu', latitude: 28, longitude: 85, utcoffset: 6, isocountrycode: 'NP' },
  { name: 'Kazan', latitude: 56, longitude: 49, utcoffset: 3, isocountrycode: 'RU' },
  { name: 'Kharkiv', latitude: 50, longitude: 36, utcoffset: 3, isocountrycode: 'UA' },
  { name: 'Khartoum', latitude: 16, longitude: 33, utcoffset: 2, isocountrycode: 'SD' },
  { name: 'Kinshasa', latitude: -4, longitude: 15, utcoffset: 1, isocountrycode: 'CD' },
  { name: 'Kingston', latitude: 18, longitude: -76, utcoffset: -5, isocountrycode: 'JM' },

  { name: 'Kigali', latitude: -2, longitude: 30, utcoffset: 2, isocountrycode: 'RW' },
  { name: 'Klaipeda', latitude: 56, longitude: 21, utcoffset: 3, isocountrycode: 'LT' },
  { name: 'Klagenfurt', latitude: 46, longitude: 14, utcoffset: 1, isocountrycode: 'AT' },
  { name: 'Kolkata', latitude: 22, longitude: 88, utcoffset: 5, isocountrycode: 'IN' },
  { name: 'Košice', latitude: 48, longitude: 21, utcoffset: 2, isocountrycode: 'SK' },
  { name: 'Köln', latitude: 51, longitude: 7, utcoffset: 1, isocountrycode: 'DE' },
  { name: 'Krasnodar', latitude: 45, longitude: 39, utcoffset: 3, isocountrycode: 'RU' },
  { name: 'Krasnoyarsk', latitude: 56, longitude: 93, utcoffset: 7, isocountrycode: 'RU' },
  { name: 'Krakow', latitude: 50, longitude: 19, utcoffset: 1, isocountrycode: 'PL' },
  { name: 'Kryvij Rih', latitude: 48, longitude: 33, utcoffset: 2, isocountrycode: 'UA' },
  { name: 'Kuala Lumpur', latitude: 3, longitude: 101, utcoffset: 8, isocountrycode: 'MY' },
  { name: 'Kuwait City', latitude: 29, longitude: 48, utcoffset: 3, isocountrycode: 'KW' },
  { name: 'Kyiv', latitude: 50, longitude: 31, utcoffset: 2, isocountrycode: 'UA' },
  { name: 'La Habana', latitude: 23, longitude: -82, utcoffset: -5, isocountrycode: 'CU' },
  { name: 'La Paz', latitude: -16, longitude: -68, utcoffset: -4, isocountrycode: 'BO' },
  { name: 'Lagos', latitude: 6, longitude: 3, utcoffset: 1, isocountrycode: 'NG' },
  { name: 'Leipzig', latitude: 51, longitude: 12, utcoffset: 1, isocountrycode: 'DE' },
  { name: 'Liberec', latitude: 50, longitude: 15, utcoffset: 1, isocountrycode: 'CZ' },
  { name: 'Lima', latitude: -12, longitude: -77, utcoffset: -5, isocountrycode: 'PE' },
  { name: 'Lisbon', latitude: 38, longitude: -9, utcoffset: 0, isocountrycode: 'PT' },
  { name: 'Ljubljana', latitude: 46, longitude: 14, utcoffset: 1, isocountrycode: 'SI' },
  { name: 'Linz', latitude: 48, longitude: 14, utcoffset: 1, isocountrycode: 'AT' },
  { name: 'Linköping', latitude: 58, longitude: 15, utcoffset: 2, isocountrycode: 'SE' },
  { name: 'London', latitude: 51, longitude: 0, utcoffset: 0, isocountrycode: 'GB' },
  { name: 'Los Angeles', latitude: 34, longitude: -118, utcoffset: -8, isocountrycode: 'US' },
  { name: 'Lomé', latitude: 6, longitude: 1, utcoffset: 0, isocountrycode: 'TG' },
  { name: 'Lubumbashi', latitude: -11, longitude: 27, utcoffset: 2, isocountrycode: 'CD' },
  { name: 'Luleå', latitude: 65, longitude: 22, utcoffset: 2, isocountrycode: 'SE' },
  { name: 'Lusaka', latitude: -15, longitude: 28, utcoffset: 2, isocountrycode: 'ZM' },
  { name: 'Luxembourg', latitude: 49, longitude: 6, utcoffset: 1, isocountrycode: 'LU' },
  { name: 'Lviv', latitude: 49, longitude: 24, utcoffset: 2, isocountrycode: 'UA' },
  { name: 'Lyon', latitude: 45, longitude: 4, utcoffset: 1, isocountrycode: 'FR' },
  { name: 'Madrid', latitude: 40, longitude: -4, utcoffset: 1, isocountrycode: 'ES' },
  { name: 'Makassar', latitude: -5, longitude: 119, utcoffset: 8, isocountrycode: 'ID' },
  { name: 'Makhačkala', latitude: 42, longitude: 47, utcoffset: 3, isocountrycode: 'RU' },
  { name: 'Malmo', latitude: 55, longitude: 13, utcoffset: 2, isocountrycode: 'SE' },
  { name: 'Manama', latitude: 26, longitude: 50, utcoffset: 3, isocountrycode: 'BH' },
  { name: 'Manaus', latitude: -3, longitude: -60, utcoffset: -4, isocountrycode: 'BR' },
  { name: 'Manchester', latitude: 53, longitude: -2, utcoffset: 0, isocountrycode: 'GB' },
  { name: 'Manila', latitude: 14, longitude: 121, utcoffset: 8, isocountrycode: 'PH' },
  { name: 'Maputo', latitude: -25, longitude: 32, utcoffset: 2, isocountrycode: 'MZ' },
  { name: 'Marrakesh', latitude: 32, longitude: -8, utcoffset: 0, isocountrycode: 'MA' },
  { name: 'Marseille', latitude: 43, longitude: 5, utcoffset: 1, isocountrycode: 'FR' },
  { name: 'Memphis', latitude: 35, longitude: -90, utcoffset: -6, isocountrycode: 'US' },
  { name: 'Mexico City', latitude: 19, longitude: -99, utcoffset: -6, isocountrycode: 'MX' },
  { name: 'Milano', latitude: 45, longitude: 9, utcoffset: 1, isocountrycode: 'IT' },
  { name: 'Minsk', latitude: 54, longitude: 28, utcoffset: 3, isocountrycode: 'BY' },
  { name: 'Monrovia', latitude: 6, longitude: -10, utcoffset: 0, isocountrycode: 'LR' },
  { name: 'Montevideo', latitude: -35, longitude: -56, utcoffset: -3, isocountrycode: 'UY' },
  { name: 'Moscow', latitude: 56, longitude: 38, utcoffset: 3, isocountrycode: 'RU' },
  { name: 'Muqdisho', latitude: 2, longitude: 45, utcoffset: 3, isocountrycode: 'SO' },
  { name: 'Mumbai', latitude: 19, longitude: 73, utcoffset: 6, isocountrycode: 'IN' },
  { name: 'Munich', latitude: 48, longitude: 12, utcoffset: 1, isocountrycode: 'DE' },
  { name: 'Murmansk', latitude: 69, longitude: 33, utcoffset: 3, isocountrycode: 'RU' },
  { name: 'Muscat', latitude: 23, longitude: 58, utcoffset: 4, isocountrycode: 'OM' },
  { name: 'Nairobi', latitude: -1, longitude: 36, utcoffset: 3, isocountrycode: 'KE' },
  { name: 'Nantes', latitude: 47, longitude: -1, utcoffset: 1, isocountrycode: 'FR' },
  { name: 'Napoli', latitude: 40, longitude: 14, utcoffset: 1, isocountrycode: 'IT' },
  { name: 'New Delhi', latitude: 28, longitude: 77, utcoffset: 6, isocountrycode: 'IN' },
  { name: 'New York', latitude: 41, longitude: -74, utcoffset: -5, isocountrycode: 'US' },
  { name: 'Nice', latitude: 43, longitude: 7, utcoffset: 1, isocountrycode: 'FR' },
  { name: 'Nicosia', latitude: 35, longitude: 33, utcoffset: 2, isocountrycode: 'CY' },
  { name: 'Niamey', latitude: 13, longitude: 2, utcoffset: 1, isocountrycode: 'NE' },
  { name: "N'Djamena", latitude: 12, longitude: 15, utcoffset: 1, isocountrycode: 'TD' },
  { name: 'Niš', latitude: 43, longitude: 22, utcoffset: 1, isocountrycode: 'RS' },
  { name: 'Nürnberg', latitude: 49, longitude: 11, utcoffset: 1, isocountrycode: 'DE' },
  { name: 'Odesa', latitude: 46, longitude: 30, utcoffset: 2, isocountrycode: 'UA' },
  { name: 'Omsk', latitude: 55, longitude: 73, utcoffset: 6, isocountrycode: 'RU' },
  { name: 'Oran', latitude: 35, longitude: 0, utcoffset: 1, isocountrycode: 'DZ' },
  { name: 'Ostrava', latitude: 49, longitude: 18, utcoffset: 1, isocountrycode: 'CZ' },
  { name: 'Oslo', latitude: 60, longitude: 11, utcoffset: 1, isocountrycode: 'NO' },
  { name: 'Ottawa', latitude: 45, longitude: -75, utcoffset: -5, isocountrycode: 'CA' },
  { name: 'Papeete', latitude: -17, longitude: -149, utcoffset: -10, isocountrycode: 'PF' },
  { name: 'Palermo', latitude: 38, longitude: 13, utcoffset: 1, isocountrycode: 'IT' },
  { name: 'Panama', latitude: 9, longitude: -79, utcoffset: -5, isocountrycode: 'PA' },
  { name: 'Paramaribo', latitude: 5, longitude: -55, utcoffset: -3, isocountrycode: 'SR' },
  { name: 'Paris', latitude: 49, longitude: 2, utcoffset: 1, isocountrycode: 'FR' },
  { name: 'Perm', latitude: 58, longitude: 56, utcoffset: 5, isocountrycode: 'RU' },
  { name: 'Perth', latitude: -31, longitude: 115, utcoffset: 8, isocountrycode: 'AU' },
  { name: 'Phnom Penh', latitude: 12, longitude: 105, utcoffset: 7, isocountrycode: 'KH' },
  { name: 'Podgorica', latitude: 42, longitude: 19, utcoffset: 1, isocountrycode: 'ME' },
  { name: 'Port of Spain', latitude: 11, longitude: -61, utcoffset: -4, isocountrycode: 'TT' },
  { name: 'Port-au-Prince', latitude: 18, longitude: -72, utcoffset: -5, isocountrycode: 'HT' },
  { name: 'Porto', latitude: 41, longitude: -8, utcoffset: 0, isocountrycode: 'PT' },
  { name: 'Porto Novo', latitude: 6, longitude: 2, utcoffset: 1, isocountrycode: 'BJ' },
  { name: 'Poznan', latitude: 52, longitude: 16, utcoffset: 1, isocountrycode: 'PL' },
  { name: 'Prague', latitude: 50, longitude: 14, utcoffset: 1, isocountrycode: 'CZ' },
  { name: 'Pristina', latitude: 42, longitude: 21, utcoffset: 1, isocountrycode: 'XK' },
  { name: 'Pyongyang', latitude: 39, longitude: 125, utcoffset: 9, isocountrycode: 'KP' },
  { name: 'Quito', latitude: 0, longitude: -79, utcoffset: -5, isocountrycode: 'EC' },
  { name: 'Reykjavik', latitude: 64, longitude: -21, utcoffset: 0, isocountrycode: 'IS' },
  { name: 'Riga', latitude: 56, longitude: 24, utcoffset: 2, isocountrycode: 'LV' },
  { name: 'Rio de Janeiro', latitude: -23, longitude: -43, utcoffset: -3, isocountrycode: 'BR' },
  { name: 'Riyadh', latitude: 24, longitude: 46, utcoffset: 3, isocountrycode: 'SA' },
  { name: 'Rome', latitude: 42, longitude: 12, utcoffset: 1, isocountrycode: 'IT' },
  { name: 'Rostov-on-Don', latitude: 47, longitude: 39, utcoffset: 3, isocountrycode: 'RU' },
  { name: 'Rovaniemi', latitude: 66, longitude: 25, utcoffset: 2, isocountrycode: 'FI' },
  { name: 'Ryazan', latitude: 54, longitude: 39, utcoffset: 3, isocountrycode: 'RU' },
  { name: 'Saratov', latitude: 51, longitude: 46, utcoffset: 4, isocountrycode: 'RU' },
  { name: 'Salzburg', latitude: 47, longitude: 13, utcoffset: 1, isocountrycode: 'AT' },
  { name: 'Samara', latitude: 53, longitude: 50, utcoffset: 4, isocountrycode: 'RU' },
  { name: 'San Juan', latitude: 18, longitude: -66, utcoffset: -4, isocountrycode: 'PR' },
  { name: 'San Jose', latitude: 10, longitude: -84, utcoffset: -6, isocountrycode: 'CR' },
  { name: 'San Marino', latitude: 43, longitude: 12, utcoffset: 1, isocountrycode: 'SM' },
  { name: 'San Salvador', latitude: 14, longitude: -89, utcoffset: -6, isocountrycode: 'SV' },
  { name: 'Santiago', latitude: -33, longitude: -70, utcoffset: -4, isocountrycode: 'CL' },
  { name: 'Santo Domingo', latitude: 18, longitude: -69, utcoffset: -4, isocountrycode: 'DO' },
  { name: 'Sao Paulo', latitude: -24, longitude: -47, utcoffset: -3, isocountrycode: 'BR' },
  { name: 'Sarajevo', latitude: 44, longitude: 18, utcoffset: 1, isocountrycode: 'BA' },
  { name: 'Sapporo', latitude: 43, longitude: 141, utcoffset: 9, isocountrycode: 'JP' },
  { name: 'Sfax', latitude: 34, longitude: 10, utcoffset: 1, isocountrycode: 'TN' },
  { name: 'Saratov', latitude: 51, longitude: 46, utcoffset: 4, isocountrycode: 'RU' },
  { name: 'Seoul', latitude: 37, longitude: 127, utcoffset: 9, isocountrycode: 'KR' },
  { name: 'Sevastopol', latitude: 44, longitude: 33, utcoffset: 3, isocountrycode: 'UA' },
  { name: 'Sevilla', latitude: 37, longitude: -5, utcoffset: 1, isocountrycode: 'ES' },
  { name: 'Shanghai', latitude: 31, longitude: 121, utcoffset: 8, isocountrycode: 'CN' },
  { name: 'Singapore', latitude: 1, longitude: 104, utcoffset: 8, isocountrycode: 'SG' },
  { name: 'Skopje', latitude: 42, longitude: 21, utcoffset: 1, isocountrycode: 'MK' },
  { name: 'Sofia', latitude: 42, longitude: 23, utcoffset: 2, isocountrycode: 'BG' },
  { name: 'Split', latitude: 43, longitude: 16, utcoffset: 1, isocountrycode: 'HR' },
  { name: 'St Petersburg', latitude: 60, longitude: 30, utcoffset: 3, isocountrycode: 'RU' },
  { name: 'Strasbourg', latitude: 48, longitude: 7, utcoffset: 1, isocountrycode: 'FR' },
  { name: 'Sucre', latitude: -19, longitude: -65, utcoffset: -4, isocountrycode: 'BO' },
  { name: 'Szeged', latitude: 46, longitude: 20, utcoffset: 1, isocountrycode: 'HU' },
  { name: 'Szczecin', latitude: 53, longitude: 14, utcoffset: 1, isocountrycode: 'PL' },
  { name: 'Stockholm', latitude: 59, longitude: 18, utcoffset: 1, isocountrycode: 'SE' },
  { name: 'Stuttgart', latitude: 48, longitude: 9, utcoffset: 1, isocountrycode: 'DE' },
  { name: 'Sydney', latitude: -34, longitude: 151, utcoffset: 10, isocountrycode: 'AU' },
  { name: 'Taipei', latitude: 25, longitude: 121, utcoffset: 8, isocountrycode: 'TW' },
  { name: 'Tampere', latitude: 61, longitude: 24, utcoffset: 2, isocountrycode: 'FI' },
  { name: 'Tartu', latitude: 58, longitude: 26, utcoffset: 3, isocountrycode: 'EE' },
  { name: 'Tallinn', latitude: 59, longitude: 24, utcoffset: 2, isocountrycode: 'EE' },
  { name: 'Tabriz', latitude: 38, longitude: 46, utcoffset: 3, isocountrycode: 'IR' },
  { name: 'Tashkent', latitude: 41, longitude: 69, utcoffset: 5, isocountrycode: 'UZ' },
  { name: 'Tbilisi', latitude: 42, longitude: 45, utcoffset: 4, isocountrycode: 'GE' },
  { name: 'Tegucigalpa', latitude: 14, longitude: -87, utcoffset: -6, isocountrycode: 'HN' },
  { name: 'Tehran', latitude: 36, longitude: 51, utcoffset: 4, isocountrycode: 'IR' },
  { name: 'Thimphu', latitude: 27, longitude: 89, utcoffset: 6, isocountrycode: 'BT' },
  { name: 'Thorshavn', latitude: 62, longitude: -7, utcoffset: 0, isocountrycode: 'FO' },
  { name: 'Thessaloniki', latitude: 40, longitude: 23, utcoffset: 2, isocountrycode: 'GR' },
  { name: 'Tirana', latitude: 41, longitude: 19, utcoffset: 1, isocountrycode: 'AL' },
  { name: 'Tokyo', latitude: 36, longitude: 140, utcoffset: 9, isocountrycode: 'JP' },
  { name: 'Timișoara', latitude: 45, longitude: 21, utcoffset: 2, isocountrycode: 'RO' },
  { name: 'Torino', latitude: 45, longitude: 7, utcoffset: 1, isocountrycode: 'IT' },
  { name: 'Tripoli', latitude: 33, longitude: 13, utcoffset: 2, isocountrycode: 'LY' },
  { name: 'Tromso', latitude: 69, longitude: 19, utcoffset: 1, isocountrycode: 'NO' },
  { name: 'Trondheim', latitude: 63, longitude: 10, utcoffset: 2, isocountrycode: 'NO' },
  { name: 'Tunis', latitude: 37, longitude: 10, utcoffset: 1, isocountrycode: 'TN' },
  { name: 'Trabzon', latitude: 41, longitude: 39, utcoffset: 3, isocountrycode: 'TR' },
  { name: 'Turku', latitude: 60, longitude: 22, utcoffset: 2, isocountrycode: 'FI' },
  { name: 'Ufa', latitude: 55, longitude: 56, utcoffset: 5, isocountrycode: 'RU' },
  { name: 'Ulaanbaatar', latitude: 48, longitude: 107, utcoffset: 8, isocountrycode: 'MN' },
  { name: 'Umeå', latitude: 63, longitude: 20, utcoffset: 2, isocountrycode: 'SE' },
  { name: 'Vaduz', latitude: 47, longitude: 9, utcoffset: 1, isocountrycode: 'LI' },
  { name: 'Valencia', latitude: 39, longitude: 0, utcoffset: 1, isocountrycode: 'ES' },
  { name: 'Valletta', latitude: 36, longitude: 14, utcoffset: 1, isocountrycode: 'MT' },
  { name: 'Vancouver', latitude: 49, longitude: -123, utcoffset: -8, isocountrycode: 'CA' },
  { name: 'Vaasa', latitude: 63, longitude: 21, utcoffset: 2, isocountrycode: 'FI' },
  { name: 'Vientiane', latitude: 18, longitude: 103, utcoffset: 7, isocountrycode: 'LA' },
  { name: 'Vienna', latitude: 48, longitude: 16, utcoffset: 1, isocountrycode: 'AT' },
  { name: 'Vilnius', latitude: 55, longitude: 25, utcoffset: 2, isocountrycode: 'LT' },
  { name: 'Vladivostok', latitude: 43, longitude: 132, utcoffset: 10, isocountrycode: 'RU' },
  { name: 'Volgograd', latitude: 48, longitude: 44, utcoffset: 4, isocountrycode: 'RU' },
  { name: 'Voronezh', latitude: 51, longitude: 39, utcoffset: 3, isocountrycode: 'RU' },
  { name: 'Warsaw', latitude: 52, longitude: 21, utcoffset: 1, isocountrycode: 'PL' },
  { name: 'Washington D.C.', latitude: 38, longitude: -77, utcoffset: -5, isocountrycode: 'US' },
  { name: 'Windhoek', latitude: -22, longitude: 17, utcoffset: 2, isocountrycode: 'NA' },
  { name: 'Wroclaw', latitude: 51, longitude: 17, utcoffset: 1, isocountrycode: 'PL' },
  { name: 'Zagreb', latitude: 46, longitude: 16, utcoffset: 1, isocountrycode: 'HR' },
  { name: 'Zurich', latitude: 47, longitude: 9, utcoffset: 1, isocountrycode: 'CH' },
];
